[package]
name = "glory-tunnel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = { version = "0.15.0", default-features = false }
sha2 = { version = "0.10", default-features = false }